version: "3.8"

services:
  localstack:
    container_name: "localstackvalidation"
    image: localstack/localstack:1.0.4
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
 
  